### ISSUE TITLE
[Datasource] text not visible in the light theme 

### ISSUE THREAD

**Issue by RudraPratik30** [ToolJet/ToolJet#10743]
### What is the expected behaviour?
In n8n datasource, the text below the dropdown should be visible in the light theme 

### What is the current behaviour?
In n8n datasource, the text below the dropdown is not visible in the light theme 

### How to reproduce the issue?

1. Go to datasources on the dashboard
2. Add **n8n** as the datasource

### Screenshots or Screencast
![image](https://github.com/user-attachments/assets/b3e4eb92-e7b0-41e7-b282-2491608ce247)
![image](https://github.com/user-attachments/assets/9344e101-47c6-45da-9d55-7ef334000b50)

**Comment by FurquanAnwer** [comment]
I would like to take this issue.

**Comment by PriteshKiri** [comment]
@FurquanAnwer  assigned. Happy coding! 

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by ElephantRohck** [comment]
Please let me know if I could contribute to it.

**Comment by Gowtz** [comment]
@PriteshKiri  i am intrested in this issue i have fixed the style
sorry i accedently pushed the commit 
i apologize for the mistake.

**Comment by PriteshKiri** [comment]
Hey @Gowtz,

Thank you for your interest! As you mentioned, we’ll have to proceed with the current approach. However, please hold onto your PR – if this issue gets reassigned, we’ll be happy to accept it. Thanks for your understanding!

**Comment by PriteshKiri** [comment]
Hey @ElephantRohck , this issue has already been assigned to @FurquanAnwer.   

Please check out other open issues under the [community contribution](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+label%3A%22community+contribution%22+no%3Aassignee) label.  Feel free to drop your queries in the contributor's channel of our [Slack community](https://tooljet.com/slack)

**Comment by FurquanAnwer** [comment]
@Gowtz hey, this is regarding setting up tooljet locally on ubuntu. How were you able to setup it ?
When I run the below commands ---
 npm run --prefix server db:create
npm run --prefix server db:reset
I get this error like --- 
Error: Command failed: createdb -h <db host> -p 5432 -U <db username> <db name>
createdb: error: could not translate host name "<db host>" to address: Name or service not known

    at checkExecSyncError (node:child_process:890:11)
    at execFileSync (node:child_process:926:15)
    at executeCreateDb (/home/furquan/tooljet/ToolJet/server/scripts/create-database.ts:60:15)
    at createDb (/home/furquan/tooljet/ToolJet/server/scripts/create-database.ts:69:5)
    at createDatabase (/home/furquan/tooljet/ToolJet/server/scripts/create-database.ts:39:11)
    at createDatabaseFromFile (/home/furquan/tooljet/ToolJet/server/scripts/create-database.ts:19:9)
    at Object.<anonymous> (/home/furquan/tooljet/ToolJet/server/scripts/create-database.ts:133:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/home/furquan/tooljet/ToolJet/server/node_modules/ts-node/src/index.ts:1618:23) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(97) [Uint8Array] [
       99, 114, 101,  97, 116, 101, 100,  98,  58,  32, 101, 114,
      114, 111, 114,  58,  32,  99, 111, 117, 108, 100,  32, 110,
      111, 116,  32, 116, 114,  97, 110, 115, 108,  97, 116, 101,
       32, 104, 111, 115, 116,  32, 110,  97, 109, 101,  32,  34,
       60, 100,  98,  32, 104, 111, 115, 116,  62,  34,  32, 116,
      111,  32,  97, 100, 100, 114, 101, 115, 115,  58,  32,  78,
       97, 109, 101,  32, 111, 114,  32, 115, 101, 114, 118, 105,
       99, 101,  32, 110, 111, 116,  32, 107, 110, 111, 119, 110,
       10
    ]
  ],
  pid: 75719,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(97) [Uint8Array] [
     99, 114, 101,  97, 116, 101, 100,  98,  58,  32, 101, 114,
    114, 111, 114,  58,  32,  99, 111, 117, 108, 100,  32, 110,
    111, 116,  32, 116, 114,  97, 110, 115, 108,  97, 116, 101,
     32, 104, 111, 115, 116,  32, 110,  97, 109, 101,  32,  34,
     60, 100,  98,  32, 104, 111, 115, 116,  62,  34,  32, 116,
    111,  32,  97, 100, 100, 114, 101, 115, 115,  58,  32,  78,
     97, 109, 101,  32, 111, 114,  32, 115, 101, 114, 118, 105,
     99, 101,  32, 110, 111, 116,  32, 107, 110, 111, 119, 110,
     10
  ]
}

> server@0.0.1 db:reset
> npm run db:drop && npm run db:setup


> server@0.0.1 db:drop
> ts-node ./scripts/drop-database.ts

database "<db name>" does not exist

Can anyone help me with this ?

**Comment by PriteshKiri** [comment]
Hey @FurquanAnwer, can you please share this in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by FurquanAnwer** [comment]
@PriteshKiri PR raised. Thanks for guiding me.

**Comment by PriteshKiri** [comment]
Thanks for your contribution @FurquanAnwer 🙌

**Comment by SauravGupta123** [comment]
@PriteshKiri can you assign this issue to me?

**Comment by PriteshKiri** [comment]
Hey @SauravGupta123 , this issue has already been assigned.

Please check out other open issues under the `community contribution` label.

**Comment by ParthParmar88** [comment]
Is this issue still valid? Can I work on this??
