### ISSUE TITLE
Error encountered when adding a datasource, with the .env LOCKBOX_MASTER_KEY and SECRET_KEY_BASE values

### ISSUE THREAD

**Issue by dvaun** [ToolJet/ToolJet#295]
### Version Information
According to `config/application.rb` I am using `TOOLJET_VERSION` 0.5.10

### Environment

* macOS Catalina 10.15.7
* Using Docker via setup under `CONTRIBUTING.md`

### What is the expected behavior?

The `LOCKBOX_MASTER_KEY` and `SECRET_KEY_BASE` values should not raise errors due to their values if they are in a standard format (e.g. base64, hex, text, etc.)

### What is the current behavior?

At present the installation seems to work correctly _except_ when attempting to add a datasource. The datasource I am attempting to add is a hosted Azure SQL instance.

The login credentials test/connect successfully from the ToolJet UI:
```txt
server_1    | Started POST "/data_sources" for 172.24.0.1 at 2021-06-22 19:39:32 +0000
server_1    | Processing by DataSourcesController#create as */*
server_1    |   Parameters: {"app_id"=>"b880494e-add4-46c7-b204-78f6ba7de9b8", "name"=>"SQL Server", "kind"=>"mssql", "options"=>[{"key"=>"host", "value"=>"****redacted****.windows.net"}, {"key"=>"port", "value"=>1433}, {"key"=>"database", "value"=>"****redacted****"}, {"key"=>"username", "value"=>"****redacted****"}, {"key"=>"password", "value"=>"****redacted****", "encrypted"=>"[FILTERED]"}, {"key"=>"azure", "value"=>true, "encrypted"=>"[FILTERED]"}], "data_source"=>{"app_id"=>"b880494e-add4-46c7-b204-78f6ba7de9b8", "name"=>"SQL Server", "options"=>[{"key"=>"host", "value"=>"****redacted****.windows.net"}, {"key"=>"port", "value"=>1433}, {"key"=>"database", "value"=>"****redacted****"}, {"key"=>"username", "value"=>"****redacted****"}, {"key"=>"password", "value"=>"****redacted****", "encrypted"=>"[FILTERED]"}, {"key"=>"azure", "value"=>true, "encrypted"=>"[FILTERED]"}], "kind"=>"mssql"}}
server_1    |   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "9e8f1e4a-6911-46b4-a149-916897526611"], ["LIMIT", 1]]
server_1    |   ↳ app/commands/authorize_api_request.rb:17:in `user'
server_1    |   Organization Load (0.6ms)  SELECT "organizations".* FROM "organizations" WHERE "organizations"."id" = $1 LIMIT $2  [["id", "32d8f64e-8ba7-4f3a-a10a-e94255454ec8"], ["LIMIT", 1]]
server_1    |   ↳ app/commands/authorize_api_request.rb:20:in `user'
server_1    |   OrganizationUser Load (0.6ms)  SELECT "organization_users".* FROM "organization_users" WHERE "organization_users"."user_id" = $1 AND "organization_users"."organization_id" = $2 ORDER BY "organization_users"."id" ASC LIMIT $3  [["user_id", "9e8f1e4a-6911-46b4-a149-916897526611"], ["organization_id", "32d8f64e-8ba7-4f3a-a10a-e94255454ec8"], ["LIMIT", 1]]
server_1    |   ↳ app/commands/authorize_api_request.rb:20:in `user'
```
 However, upon saving the credentials the UI hangs as it doesn't react to the error thrown on the backend:
```txt
server_1    | Completed 500 Internal Server Error in 28ms (ActiveRecord: 4.9ms | Allocations: 5052)
server_1    |
server_1    |
server_1    |
server_1    | Lockbox::Error (Master key must use binary encoding):
server_1    |
server_1    | app/controllers/data_sources_controller.rb:14:in `block in create'
server_1    | app/controllers/data_sources_controller.rb:12:in `each'
server_1    | app/controllers/data_sources_controller.rb:12:in `create'
```
I attempted various sets of values.
For example:
* `LOCKBOX_MASTER_KEY=2xVkIwzC1a33pE7zntKSDAHQCoRbqM8K`

I took a look at https://github.com/ankane/lockbox and decided that I should try a hex-based value instead:
* `LOCKBOX_MASTER_KEY=4d366149526a5272426a6a414f765251`
This didn't work either. I searched through the issues here and didn't find any relevant issues.
### How to reproduce the issue?

1. Run `git clone https://github.com/ToolJet/ToolJet` and follow setup instructions in `CONTRIBUTING.md` for a Docker installation
2. Place values into `BASE_DIR/.env` for `LOCKBOX_MASTER_KEY` and `SECRET_KEY_BASE`
3. Start the server and client
4. Create a new app. Attempt to add an Azure SQL Server datasource

### Please provide any traces or logs that could help here.
See logs provided above

At the following is the return value from the POST request sent to `/data_sources` when attempting to create the datasource: https://pastebin.com/L1WV4en4

### Any possible solutions?

After looking at https://github.com/ankane/blind_index/issues/15 and https://github.com/ankane/lockbox/blob/master/lib/lockbox/aes_gcm.rb I think that something can be done with converting the key format.

### If the bug is confirmed, would you be willing to submit a PR?

Time permitting, yes

**Comment by dvaun** [comment]
Update: It looks like I didn't read thoroughly. From the documentation, I ran `openssl rand -hex 64` and replaced both keys. That raised an error ("Master key must be 32 bytes (64 hex digits)")—I tried with `32` and it worked.

My keys were not long enough. Simple fix.
