### ISSUE TITLE
Error: Command failed: PGPASSWORD=... createdb -h ... -p 5432 -U ... ...

### ISSUE THREAD

**Issue by junkei-okinawa** [ToolJet/ToolJet#2951]
### Version Information
image: tooljet/tooljet-ce:latest

### Environment
MacOS 12.3.1

### What is the expected behaviour?
I want to connect to Postgres in the same Namespace with kubernetes and start the tooljet server.

### What is the current behaviour?
Using [this page](https://docs.tooljet.com/docs/setup/kubernetes) as a reference, I ran kubectl apply -f deployment.yaml with reference to the secret information in Namespace, but I get an error because PG_PASS contains "(".

### How to reproduce the issue?
1.Download deployment.yaml.
```bash
wget https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/kubernetes/deployment.yaml
```
2.Edit env information in deployment.yaml.
```deployment.yaml
          env:
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: secret-example
                key: dbname
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: secret-example
                key: user
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: secret-example
                key: host
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: secret-example
                key: port
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: secret-example
                key: password
```
3.
```bash
kubectl -n namespace-example logs tooljet-deployment-57b7fc5bb9-lgbst

> @ db:create /app
> npm --prefix server run db:create


> server@0.0.1 db:create /app/server
> ts-node ./scripts/create-database.ts

/app/.env file not found to create database
Picking up config from the environment
Error: Command failed: PGPASSWORD=(Y@WjRznZS;************* createdb -h ************** -p 5432 -U ****** ******
/bin/sh: 1: Syntax error: "(" unexpected

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at ChildProcess.emit (domain.js:470:12)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at Pipe.<anonymous> (net.js:675:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'PGPASSWORD=(Y@WjRznZS;************* createdb -h ************** -p 5432 -U ****** ******
}

> @ db:migrate /app
> npm --prefix server run db:migrate


> server@0.0.1 db:migrate /app/server
> ts-node -r tsconfig-paths/register --transpile-only ./node_modules/typeorm/cli.js migration:run

```

### Any possible solutions?
This can be avoided by writing the environment variables to .env.
Write the command and args of deployment.yaml as follows.
```deployment.yaml
        command: ["bash", "-c"]
        args:
          - |
            echo "PG_DB=${PG_DB}" > /app/.env
            echo "PG_USER=${PG_USER}" >> /app/.env
            echo "PG_HOST=${PG_HOST}" >> /app/.env
            echo "PG_PASS=${PG_PASS}" >> /app/.env
            echo "SERVE_CLIENT=${SERVE_CLIENT}" >> /app/.env
            echo "LOCKBOX_MASTER_KEY=${LOCKBOX_MASTER_KEY}" >> /app/.env
            echo "SECRET_KEY_BASE=${SECRET_KEY_BASE}" >> /app/.env
            echo "CHECK_FOR_UPDATES=${CHECK_FOR_UPDATES}" >> /app/.env
            echo "DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}" >> /app/.env
            echo "ORM_LOGGING=${ORM_LOGGING}" >> /app/.env
            npm run start:prod

```
### If the bug is confirmed, would you be willing to submit a PR?
Maybe

**Comment by withshubh** [comment]
@akshaysasidrn Please take a look at this issue

**Comment by akshaysasidrn** [comment]
Hey @junkei-okinawa, it looks like node internally runs this on the default shell, which interprets it as an unexpected token.
We can fix this by wrapping the password in double-quotes [here](https://github.com/ToolJet/ToolJet/blob/develop/server/scripts/create-database.ts#L34). Feel free to open a PR with the fix.
