### ISSUE TITLE
docker版本本地无法运行

### ISSUE THREAD

**Issue by leqii-com** [ToolJet/ToolJet#3378]
docker run \
  --name tooljet \
  --restart unless-stopped \
  -p 3000:3000 \
  -v tooljet_data:/var/lib/postgresql/13/main \
  tooljet/try:latest

用官网上面这个命令无法运行docker，容器起不来，容器 反复重启，日志也没有输出，不知道什么原因

**Comment by leqii-com** [comment]
后面又去下载了 其它版本 docker pull tooljet/tooljet-ce
报如下错误：
Error: Config validation error: "PG_USER" is required
    at createDatabase (/app/server/dist/scripts/create-database.js:18:15)
    at Object.<anonymous> (/app/server/dist/scripts/create-database.js:57:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by akshaysasidrn** [comment]
Hey @leqii-com, `tooljet/try` is meant to try out tooljet locally. If you are to use `tooljet/tooljet-ce`, then you'd have to configure for postgres db. Which can be configure with `PG_*` env values.
