### ISSUE TITLE
Cannot build tooljet-client:development Docker image

### ISSUE THREAD

**Issue by frafra** [ToolJet/ToolJet#4820]
### Version Information
devel, 86917971a6fb12575c642fdff4e9d7725472eb3a

### Environment
Docker

### What is the expected behaviour?
The compose stack should build successfully when running `docker compose build`.

### What is the current behaviour?

It is not possible to build the `tooljet-client:development` image.

### How to reproduce the issue?

1. Checkout develop
2. `cp .env.example .env` and update `.env`
3. `docker compose build`

### Please provide any traces or logs that could help here.
```
 => CANCELED [tooljet-client:development 6/7] RUN npm --prefix frontend install                                                                                                                       0.5s
------                                                                                                                                                                                                     
 > [tooljet-plugins:development 6/7] RUN npm --prefix plugins install:                                                                                                                                     
#0 0.537 TypeError: Class extends value undefined is not a constructor or null                                                                                                                             
#0 0.537     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)                                                                                   
#0 0.537     at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                                                                                   
#0 0.537     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                                                                                     
#0 0.537     at Module.load (internal/modules/cjs/loader.js:950:32)
#0 0.537     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
#0 0.537     at Module.require (internal/modules/cjs/loader.js:974:19)
#0 0.537     at require (internal/modules/cjs/helpers.js:92:18)
#0 0.537     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
#0 0.537     at Module._compile (internal/modules/cjs/loader.js:1085:14)
#0 0.537     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
#0 0.537     at Module.load (internal/modules/cjs/loader.js:950:32)
#0 0.537     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
#0 0.537     at Module.require (internal/modules/cjs/loader.js:974:19)
#0 0.537     at require (internal/modules/cjs/helpers.js:92:18)
#0 0.537     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
#0 0.537     at Module._compile (internal/modules/cjs/loader.js:1085:14)
------
failed to solve: executor failed running [/bin/sh -c npm --prefix plugins install]: exit code: 1
```

### If the bug is confirmed, would you be willing to submit a PR?
I do not know what is causing the issue.

**Comment by frafra** [comment]
It seems an obscure Docker issue.

Installing npm twice using two commands, does not work:

```
RUN npm i -g npm@7.20.0
RUN npm i -g npm@7.20.0
```

Installing them at once does not produce any error:
```
RUN npm i -g npm@7.20.0 && npm i -g npm@7.20.0
```

This also works:

`RUN npm i -g npm@7.20.0 && npm --prefix plugins install`

**Comment by frafra** [comment]
```
RUN npm i npm@7.20.0 && \
    rm -rf /usr/local/lib/node_modules/npm && \
    mv node_modules/npm /usr/local/lib/node_modules/npm
```

This seems to fix the issue.

**Comment by frafra** [comment]
I discovered various Docker issue. I will stop reporting now, waiting for your feedbacks on how to proceed.

**Comment by withshubh** [comment]
Hey @frafra 
This issue is related to setting up ToolJet. Closing the issue, please ask the same in our [Slack community](https://www.tooljet.com)

**Comment by frafra** [comment]
Hey :-)
This is not a support request, but a specific bug to code belonging to the repository.

**Comment by akshaysasidrn** [comment]
Hey @frafra, I am unable to replicate the same on the latest develop. Could it be that you had tried installing tooljet locally and then when the node_modules folder is copied in docker env, it is failing to build? Could you try removing the node_modules dir and then try docker build once again?

**Comment by frafra** [comment]
Hey @akshaysasidrn. I never tried to develop without Docker, and no `node_modules` directory is found.
I cloned again, using the latest develop, and the problem is 100 % reproducible.

It seems that there is something happening with some environmental variable, such as PATH or similar, as the behavior changes based on the fact that the commands are executed inside the same shell as the npm upgrade/downgrade or not.

Here is my Docker version:
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:04 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by frafra** [comment]
I can confirm that the issue still persists. `npm --prefix frontend install` fails.
