### ISSUE TITLE
Server error on running test connection for ReThink DB

### ISSUE THREAD

**Issue by emidhun** [ToolJet/ToolJet#5620]
### Environment
Develop

### What is the expected behaviour?
 
 Test connection should show a error message on connection verified status.

### What is the current behaviour?

1. Showing the error message but not able to save any app modifications after that.
2. From second try it shoes blank toast message.

### How to reproduce the issue?

*  Add new app.
* Add rethinkDB.
* Click on test connection.
* Click once again.

### Screenshots or Screencast

https://user-images.githubusercontent.com/20367955/220826275-6a066e67-e0f4-409f-aaec-f6e9060062ed.mp4

### Please provide any traces or logs that could help here.
Server log : 
```ERROR [02/23/2023, 4:22:11 AM UTC] (ReqlDriverError/68259 on Midhuns-MacBook-Pro.local): Could not connect to localhost:28015.
connect ECONNREFUSED ::1:28015
    ReqlDriverError: Could not connect to localhost:28015.
    connect ECONNREFUSED ::1:28015
        at ReqlDriverError.ReqlError [as constructor] (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/node_modules/rethinkdb/errors.js:23:13)
        at new ReqlDriverError (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/node_modules/rethinkdb/errors.js:68:50)
        at TcpConnection.<anonymous> (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/node_modules/rethinkdb/net.js:94:27)
        at Object.onceWrapper (node:events:642:26)
        at TcpConnection.emit (node:events:527:28)
        at TcpConnection.emit (node:domain:475:12)
        at Socket.<anonymous> (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/node_modules/rethinkdb/net.js:705:22)
        at Socket.emit (node:events:539:35)
        at Socket.emit (node:domain:475:12)
        at emitErrorNT (node:internal/streams/destroy:151:8)
        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
        at processTicksAndRejections (node:internal/process/task_queues:82:21)
    From previous event:
        at Function.<anonymous> (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/node_modules/rethinkdb/net.js:947:10)
        at Function.connect (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/node_modules/rethinkdb/util.js:43:16)
        at Rethinkdb.<anonymous> (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/packages/rethinkdb/lib/index.ts:89:20)
        at Generator.next (<anonymous>)
        at /Users/emidhun/tooljetWorkspace/ToolJet/plugins/dist/packages/rethinkdb/lib/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/dist/packages/rethinkdb/lib/index.js:4:12)
        at Rethinkdb.getConnection (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/dist/packages/rethinkdb/lib/index.js:240:16)
        at Rethinkdb.<anonymous> (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/packages/rethinkdb/lib/index.ts:107:35)
        at Generator.next (<anonymous>)
        at /Users/emidhun/tooljetWorkspace/ToolJet/plugins/dist/packages/rethinkdb/lib/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/dist/packages/rethinkdb/lib/index.js:4:12)
        at Rethinkdb.testConnection (/Users/emidhun/tooljetWorkspace/ToolJet/plugins/dist/packages/rethinkdb/lib/index.js:253:16)
        at DataSourcesService.testConnection (/Users/emidhun/tooljetWorkspace/ToolJet/server/src/services/data_sources.service.ts:269:30)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at DataSourcesController.testConnection (/Users/emidhun/tooljetWorkspace/ToolJet/server/src/controllers/data_sources.controller.ts:128:12)
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:377:5)
    at ServerResponse.setHeader (node:_http_outgoing:595:11)
    at ServerResponse.header (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/response.js:278:15)
    at AllExceptionsFilter.catch (/Users/emidhun/tooljetWorkspace/ToolJet/server/src/all-exceptions-filter.ts:41:43)
    at ExceptionsHandler.invokeCustomFilters (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
    at ExceptionsHandler.next (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
    at /Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/@nestjs/core/router/router-proxy.js:24:35
    at Layer.handle_error (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:326:13)
    at /Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle_error (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:326:13)
    at /Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle_error (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:326:13)
    at /Users/emidhun/tooljetWorkspace/ToolJet/server/node_modules/express/lib/router/index.js:286:9```

**Comment by shubh22** [comment]
Issue doesnt exist anymore. Closing it.
