### ISSUE TITLE
Unable to set up simple Docker environment with Tooljet DB

### ISSUE THREAD

**Issue by ArchiDevil** [ToolJet/ToolJet#5751]
### Version Information
Latest `toolject/toolject-ce` container at the current moment.

### Environment
Docker for Windows 4.17, example `.env` file with the following content (I removed empty fields):

```
TOOLJET_HOST=http://localhost:8082
LOCKBOX_MASTER_KEY=b6864a5a05ec4dfa2099bfe70f81a4b8849df771dc637acf2451c96bdc42ab05
SECRET_KEY_BASE=88a207575ff63f97c9b6bb324f8de26afbd83cb15a8ed1c554001fd7df5dc2f320ca94f9c9ba76df650c1b7e05a596c7751b65bfc8e4e2a3241d3bcb9ee40673

ORM_LOGGING=all
PG_DB=tooljet_production
PG_USER=postgres
PG_HOST=postgres
PG_PASS=postgres

CHECK_FOR_UPDATES=0

DISABLE_SIGNUPS=true

ENABLE_MULTIPLAYER_EDITING=true
ENABLE_TOOLJET_DB=true
PGRST_JWT_SECRET=b6864a5a05ec4dfa2099bfe70f81a4b8849df771dc637acf2451c96bdc42ab05
PGRST_DB_URI=postgres://postgres:postgres@postgres:5432/tooljet_db
TOOLJET_DB_HOST=postgres
TOOLJET_DB_USER=postgres
TOOLJET_DB_PASS=postgres

#TELEMETRY
DEPLOYMENT_PLATFORM=docker
```

`docker-compose.yml` content is the default but with uncommented `postgrest` service.

### What is the expected behaviour?
Tool starts and works as usual with TooljetDB available to use.

### What is the current behaviour?
Tool unable to set up its main container `tooljet` which if failing repeatedly and restarting.

The log contains the following lines:

```
2023-03-14 17:46:18 query: CREATE EXTENSION IF NOT EXISTS "pgcrypto"
2023-03-14 17:46:18 query: SELECT * FROM current_schema()
2023-03-14 17:46:18 query: SHOW server_version;
2023-03-14 17:46:18 node:internal/process/promises:288
2023-03-14 17:46:18             triggerUncaughtException(err, true /* fromPromise */);
2023-03-14 17:46:18             ^
2023-03-14 17:46:18 
2023-03-14 17:46:18 AssertionError [ERR_ASSERTION]: Host should not be empty
2023-03-14 17:46:18     at proxy (/app/server/node_modules/express-http-proxy/index.js:27:3)
2023-03-14 17:46:18     at new PostgrestProxyService (/app/server/dist/src/services/postgrest_proxy.service.js:25:26)
2023-03-14 17:46:18     at Injector.instantiateClass (/app/server/node_modules/@nestjs/core/injector/injector.js:287:19)
2023-03-14 17:46:18     at callback (/app/server/node_modules/@nestjs/core/injector/injector.js:43:41)
2023-03-14 17:46:18     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-03-14 17:46:18     at async Injector.resolveConstructorParams (/app/server/node_modules/@nestjs/core/injector/injector.js:115:24)
2023-03-14 17:46:18     at async Injector.loadInstance (/app/server/node_modules/@nestjs/core/injector/injector.js:47:9)
2023-03-14 17:46:18     at async Injector.loadProvider (/app/server/node_modules/@nestjs/core/injector/injector.js:69:9)
2023-03-14 17:46:18     at async Promise.all (index 4)
2023-03-14 17:46:18     at async InstanceLoader.createInstancesOfProviders (/app/server/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
2023-03-14 17:46:18     at async /app/server/node_modules/@nestjs/core/injector/instance-loader.js:29:13
2023-03-14 17:46:18     at async Promise.all (index 4)
2023-03-14 17:46:18     at async InstanceLoader.createInstances (/app/server/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
2023-03-14 17:46:18     at async InstanceLoader.createInstancesOfDependencies (/app/server/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
2023-03-14 17:46:18     at async /app/server/node_modules/@nestjs/core/nest-factory.js:93:17
2023-03-14 17:46:18     at async ExceptionsZone.asyncRun (/app/server/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
2023-03-14 17:46:18     at async NestFactoryStatic.initialize (/app/server/node_modules/@nestjs/core/nest-factory.js:91:13)
2023-03-14 17:46:18     at async NestFactoryStatic.create (/app/server/node_modules/@nestjs/core/nest-factory.js:37:9)
2023-03-14 17:46:18     at async bootstrap (/app/server/dist/src/main.js:18:17) {
2023-03-14 17:46:18   generatedMessage: false,
2023-03-14 17:46:18   code: 'ERR_ASSERTION',
2023-03-14 17:46:18   actual: undefined,
2023-03-14 17:46:18   expected: true,
2023-03-14 17:46:18   operator: '=='
2023-03-14 17:46:18 }
```

### How to reproduce the issue?

1. Download `docker-compose.yml` and `.env` files from repo
2. Put provided config from the beginning of the post to the `.env` file and uncomment `postgrest` service in `docker-compose.yml` file
3. Create a `postgres_data` directory
4. Run `docker compose up -d` in the directory where compose and env files are located.

**Comment by withshubh** [comment]
Hey @ArchiDevil - Thanks for creating the issue. We will check this and get back to you.

**Comment by adishM98** [comment]
Hi @ArchiDevil, 

Could try adding the below variables: 

TOOLJET_DB=tooljet_db
PGRST_HOST=postgrest

After adding try restarting the containers.

**Comment by ArchiDevil** [comment]
@adishM98, with these setting it seems working now. But it is very unclear from the documentation that user must use all parameters from configuration and logging tells nothing about `PGRST_HOST` variable, just some host is unknown. Are there any plans to update docs, making them clearer?

**Comment by adishM98** [comment]
@ArchiDevil, 

Yes, we are on updating the docs. Will make these changes.
