### ISSUE TITLE
[can't start new thread while performing boto3.resource.copy operation]

### ISSUE THREAD

**Issue by mojuss** [ToolJet/ToolJet#6504]
### Version Information
tooljet cloud Version 2.5.0-ee2.0.15-cloud2.0.2
### What is the expected behaviour?
I'm using python query. I want to copy object from one catalogue to another, within the same bucket. So technically, I'm creating an object with different key.

### What is the current behaviour?
I'm getting an error, that 

### How to reproduce the issue?

1. Create a new python query in the tooljet cloud (I've checked on multiple browsers: Chrome and EDGE, e.g. Chrome Version 109.0.5414.120 (Official Build) (64-bit))
3. Add the code:

import micropip
pcg_list = str(micropip.list())
await micropip.install('urllib3==1.25.4')
await micropip.install('pyyaml==6.0')
await micropip.install('boto3',keep_going=True)

import boto3, threading
boto3.set_stream_logger('botocore', level='DEBUG')
import ssl
import urllib3
import ssl
import urllib3

bucket = "your_bucket_name"
region = "your region" # in my case it is eu-west-1
access_key = "your_access_key" #generated for your user
secret_key="your_secret_key" #generated for your user
source_key="key_to_the_object_you_want_to_copy"
target_key="key_to_the_object_you_create"

s3_resource = boto3.resource('s3', region_name=region, aws_access_key_id=access_key, aws_secret_access_key=secret_key).Bucket(bucket)

# Copy object A as object B
copy_source = {"Bucket": bucket, "Key":source_key }
print("threading: ", threading.active_count()) #I'm getting always counter = 1
s3_resource.copy(copy_source, target_key)
print("bucket get: ", copy_source)
# Copy object A as object B
print('finished')

### Please provide any traces or logs that could help here.
The listing from the error:
**threading:  1**

vendor.js?31004aadaf21cab670d4:827 appUtils.js (136:6) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 531, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 26, in <module>
  File "/lib/python3.10/site-packages/boto3/s3/inject.py", line 502, in bucket_copy
    return self.meta.client.copy(
  File "/lib/python3.10/site-packages/boto3/s3/inject.py", line 436, in copy
    future = manager.copy(
  File "/lib/python3.10/site-packages/s3transfer/manager.py", line 446, in copy
    return self._submit_transfer(call_args, CopySubmissionTask)
  File "/lib/python3.10/site-packages/s3transfer/manager.py", line 528, in _submit_transfer
    self._submission_executor.submit(
  File "/lib/python3.10/site-packages/s3transfer/futures.py", line 474, in submit
    future = ExecutorFuture(self._executor.submit(task))
  File "/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/lib/python3.10/threading.py", line 928, in start
    **_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread**

    at new_error (pyodide.asm.js:10:179954)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xee978
    at method_call_trampoline (pyodide.asm.js:10:229349)
    at pyodide.asm.wasm:0x1313a1
    at pyodide.asm.wasm:0x202469
    at pyodide.asm.wasm:0x16ca9e
    at pyodide.asm.wasm:0x1318b5
    at pyodide.asm.wasm:0x1319af
    at pyodide.asm.wasm:0x131a52
    at pyodide.asm.wasm:0x1eb770
    at pyodide.asm.wasm:0x1e579f
    at pyodide.asm.wasm:0x131a95
    at pyodide.asm.wasm:0x1ed552
    at pyodide.asm.wasm:0x1eb1b2
    at pyodide.asm.wasm:0x1e579f
    at pyodide.asm.wasm:0x131a95
    at pyodide.asm.wasm:0xee1af
    at pyodide.asm.wasm:0xee050
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:219389)
    at N (vendor.js?31004aadaf21cab670d4:812:56658)

### Can you identify the location in the driver source code where the problem exists?
pyodide?

### If the bug is confirmed, would you be willing to submit a PR?
yes.

**Comment by mojuss** [comment]
just one important information. the boto3.resource.copy operation does work well, once it is executed out of the browser (e.g. PyCharm). The same credentials, bucket, keys are being used.
So there I conclude it is not s3 bucket/object access issue, but with that in the browser, somehow, I'm blocked to only one thread at a time.
