### ISSUE TITLE
The service cannot start without PGRST_HOST

### ISSUE THREAD

**Issue by Tarocch1** [ToolJet/ToolJet#7554]
### Version Information

v2.19.0

### Environment

Docker

### What is the expected behaviour?

ToolJet can start without `PGRST_HOST` environment variable.

### What is the current behaviour?

When the `ENABLE_TOOLJET_DB` is set to false and the `PGRST_HOST` is not configured, the service cannot start. 

Error log:

```
2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] AssertionError [ERR_ASSERTION]: Host should not be empty

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at proxy (/app/server/node_modules/express-http-proxy/index.js:27:3)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at new PostgrestProxyService (/app/server/dist/src/services/postgrest_proxy.service.js:25:26)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at Injector.instantiateClass (/app/server/node_modules/@nestjs/core/injector/injector.js:287:19)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at callback (/app/server/node_modules/@nestjs/core/injector/injector.js:43:41)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async Injector.resolveConstructorParams (/app/server/node_modules/@nestjs/core/injector/injector.js:115:24)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async Injector.loadInstance (/app/server/node_modules/@nestjs/core/injector/injector.js:47:9)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async Injector.loadProvider (/app/server/node_modules/@nestjs/core/injector/injector.js:69:9)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async Promise.all (index 13)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async InstanceLoader.createInstancesOfProviders (/app/server/node_modules/@nestjs/core/injector/instance-loader.js:44:9)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async /app/server/node_modules/@nestjs/core/injector/instance-loader.js:29:13

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async Promise.all (index 55)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async InstanceLoader.createInstances (/app/server/node_modules/@nestjs/core/injector/instance-loader.js:28:9)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async InstanceLoader.createInstancesOfDependencies (/app/server/node_modules/@nestjs/core/injector/instance-loader.js:18:9)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async /app/server/node_modules/@nestjs/core/nest-factory.js:93:17

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async ExceptionsZone.asyncRun (/app/server/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async NestFactoryStatic.initialize (/app/server/node_modules/@nestjs/core/nest-factory.js:91:13)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async NestFactoryStatic.create (/app/server/node_modules/@nestjs/core/nest-factory.js:37:9)

2023-09-29T14:28:11.342 app[3d8d9503f56189] hkg [info] at async bootstrap (/app/server/dist/src/main.js:35:17)
```

It seems that the `PostgrestProxyService` initializes and attempts to read the `PGRST_HOST` during startup, and if it's not set, it results in an error.

https://github.com/ToolJet/ToolJet/blob/105a8af6411f27c7cc1ccb290d1d297e37f42e4c/server/src/services/postgrest_proxy.service.ts#L27-L37

Before v2.19.0, if the ToolJet Database is not enabled, the service shouldn't attempt to load the `PostgrestProxyService`. But In v2.19.0, it seems that `PostgrestProxyService` is being loaded regardless of whether the `ENABLE_TOOLJET_DB` is set, which leads to a startup error.

**Comment by akshaysasidrn** [comment]
This issue has been resolved
