### ISSUE TITLE
npm run build:plugins.  error. 

### ISSUE THREAD

**Issue by zhuyihero** [ToolJet/ToolJet#8147]
### Version Information
develop

### Environment

MacOS (Apple M2 Max)
### What is the expected behaviour?

Follow https://docs.tooljet.com/docs/contributing-guide/setup/macos 

 npm run build:plugins not fail

### What is the current behaviour?

Run npm run build:plugins fail 
error message:
> @tooljet/plugins@0.0.1 clean:packages
> node clean-packages.js

node:internal/modules/cjs/loader:362
      throw err;
      ^

Error: Cannot find module '/Users/yi.zhu/code/tooljet/plugins/node_modules/gauge/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:354:19)
    at Module._findPath (node:internal/modules/cjs/loader:567:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/yi.zhu/code/tooljet/plugins/node_modules/npmlog/log.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/yi.zhu/code/tooljet/plugins/node_modules/gauge/package.json',
  requestPath: 'gauge'
}

Node.js v18.3.0
node:child_process:891
    throw err;
    ^

Error: Command failed: npx lerna run clean --parallel --no-private
node:internal/modules/cjs/loader:362
      throw err;
      ^

Error: Cannot find module '/Users/yi.zhu/code/tooljet/plugins/node_modules/gauge/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:354:19)
    at Module._findPath (node:internal/modules/cjs/loader:567:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/yi.zhu/code/tooljet/plugins/node_modules/npmlog/log.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/yi.zhu/code/tooljet/plugins/node_modules/gauge/package.json',
  requestPath: 'gauge'
}

Node.js v18.3.0

    at checkExecSyncError (node:child_process:817:11)
    at execSync (node:child_process:888:15)
    at Object.<anonymous> (/Users/yi.zhu/code/tooljet/plugins/clean-packages.js:6:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,

### How to reproduce the issue?

1.
2.
3.

### Please provide any traces or logs that could help here.
Try to brew install gauge or npm install gauge but not working.

**Comment by akshaysasidrn** [comment]
@zhuyihero, I am unable to replicate this on the latest `development`. Please re-open the issue if updating it does not solve for you.

Also note that some of the dependencies may not build on ARM chip of M2. So, I would like to advise you to run the build through the rosetta terminal.
