### ISSUE TITLE
AddUniqueConstraintToWorkspaceName fails on trying to run v.2.1.0 backup

### ISSUE THREAD

**Issue by pbjorklund** [ToolJet/ToolJet#9374]
### Version Information
2.1.0 -> latest

### Environment
docker
ubuntu

### What is the expected behaviour?
to be able to run a backup of prod locally

### What is the current behaviour?
migrations fail

### How to reproduce the issue?

```docker-compose
version: '3'

services:
  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    env_file: .env
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
      # - /replace_path_here/nginx.conf.template:/etc/openresty/nginx.conf.template
    ports:
      - 80:80
      - 443:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    env_file: .env
    environment:
      SERVE_CLIENT: "false"
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=redacted

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres_data
  certs:
  logs:
  fallbackcerts:
```

1. restore backup running v2.1.0
2. docker compose up
3. failure

### Please provide any traces or logs that could help here.

```
server-1    | 92 migrations are already loaded in the database.
server-1    | 75 migrations were found in the source code.
server-1    | addDataSourceType1671815159504 is the last executed migration. It was executed on Fri Dec 23 2022 17:05:59 GMT+0000 (Coordinated Universal Time).
server-1    | 19 migrations are new migrations that needs to be executed.
```

```
server-1    | query failed: SELECT "Organization"."id" AS "Organization_id", "Organization"."name" AS "Organization_name", "Organization"."slug" AS "Organization_slug", "Organization"."domain" AS "Organization_domain", "Organization"."enable_sign_up" AS "Organization_enable_sign_up", "Organization"."inherit_sso" AS "Organization_inherit_sso", "Organization"."created_at" AS "Organization_created_at", "Organization"."updated_at" AS "Organization_updated_at" FROM "organizations" "Organization" WHERE "Organization"."name" = $1 -- PARAMETERS: ["xxx"]
server-1    | error: error: column Organization.slug does not exist
server-1    |     at Parser.parseErrorMessage (/app/server/node_modules/pg-protocol/dist/parser.js:287:98)
server-1    |     at Parser.handlePacket (/app/server/node_modules/pg-protocol/dist/parser.js:126:29)
server-1    |     at Parser.parse (/app/server/node_modules/pg-protocol/dist/parser.js:39:38)
server-1    |     at Socket.<anonymous> (/app/server/node_modules/pg-protocol/dist/index.js:11:42)
server-1    |     at Socket.emit (node:events:527:28)
server-1    |     at Socket.emit (node:domain:475:12)
server-1    |     at addChunk (node:internal/streams/readable:324:12)
server-1    |     at readableAddChunk (node:internal/streams/readable:297:9)
server-1    |     at Readable.push (node:internal/streams/readable:234:10)
server-1    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
server-1    |   length: 115,
server-1    |   severity: 'ERROR',
server-1    |   code: '42703',
server-1    |   detail: undefined,
server-1    |   hint: undefined,
server-1    |   position: '96',
server-1    |   internalPosition: undefined,
server-1    |   internalQuery: undefined,
server-1    |   where: undefined,
server-1    |   schema: undefined,
server-1    |   table: undefined,
server-1    |   column: undefined,
server-1    |   dataType: undefined,
server-1    |   constraint: undefined,
server-1    |   file: 'parse_relation.c',
server-1    |   line: '3553',
server-1    |   routine: 'errorMissingColumn'
server-1    | }
server-1    | Migration "AddUniqueConstraintToWorkspaceName1683136077244" has been failed, error: column Organization.slug does not exist
server-1    | query: ROLLBACK
server-1    | Error during migration run:
server-1    | QueryFailedError: column Organization.slug does not exist
server-1    |     at QueryFailedError.TypeORMError [as constructor] (/app/server/node_modules/typeorm/error/TypeORMError.js:9:28)
server-1    |     at new QueryFailedError (/app/server/node_modules/typeorm/error/QueryFailedError.js:13:28)
server-1    |     at PostgresQueryRunner.<anonymous> (/app/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)
server-1    |     at step (/app/server/node_modules/tslib/tslib.js:143:27)
server-1    |     at Object.throw (/app/server/node_modules/tslib/tslib.js:124:57)
server-1    |     at rejected (/app/server/node_modules/tslib/tslib.js:115:69)
server-1    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
server-1    |   query: 'SELECT "Organization"."id" AS "Organization_id", "Organization"."name" AS "Organization_name", "Organization"."slug" AS "Organization_slug", "Organization"."domain" AS "Organization_domain", "Organization"."enable_sign_up" AS "Organization_enable_sign_up", "Organization"."inherit_sso" AS "Organization_inherit_sso", "Organization"."created_at" AS "Organization_created_at", "Organization"."updated_at" AS "Organization_updated_at" FROM "organizations" "Organization" WHERE "Organization"."name" = $1',
server-1    |   parameters: [ 'xxxx' ],
server-1    |   driverError: error: column Organization.slug does not exist
server-1    |       at Parser.parseErrorMessage (/app/server/node_modules/pg-protocol/dist/parser.js:287:98)
server-1    |       at Parser.handlePacket (/app/server/node_modules/pg-protocol/dist/parser.js:126:29)
server-1    |       at Parser.parse (/app/server/node_modules/pg-protocol/dist/parser.js:39:38)
server-1    |       at Socket.<anonymous> (/app/server/node_modules/pg-protocol/dist/index.js:11:42)
server-1    |       at Socket.emit (node:events:527:28)
server-1    |       at Socket.emit (node:domain:475:12)
server-1    |       at addChunk (node:internal/streams/readable:324:12)
server-1    |       at readableAddChunk (node:internal/streams/readable:297:9)
server-1    |       at Readable.push (node:internal/streams/readable:234:10)
server-1    |       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
server-1    |     length: 115,
server-1    |     severity: 'ERROR',
server-1    |     code: '42703',
server-1    |     detail: undefined,
server-1    |     hint: undefined,
server-1    |     position: '96',
server-1    |     internalPosition: undefined,
server-1    |     internalQuery: undefined,
server-1    |     where: undefined,
server-1    |     schema: undefined,
server-1    |     table: undefined,
server-1    |     column: undefined,
server-1    |     dataType: undefined,
server-1    |     constraint: undefined,
server-1    |     file: 'parse_relation.c',
server-1    |     line: '3553',
server-1    |     routine: 'errorMissingColumn'
server-1    |   },
server-1    |   length: 115,
server-1    |   severity: 'ERROR',
server-1    |   code: '42703',
server-1    |   detail: undefined,
server-1    |   hint: undefined,
server-1    |   position: '96',
server-1    |   internalPosition: undefined,
server-1    |   internalQuery: undefined,
server-1    |   where: undefined,
server-1    |   schema: undefined,
server-1    |   table: undefined,
server-1    |   column: undefined,
server-1    |   dataType: undefined,
server-1    |   constraint: undefined,
server-1    |   file: 'parse_relation.c',
server-1    |   line: '3553',
server-1    |   routine: 'errorMissingColumn'
server-1    | }
server-1 exited with code 1
```

### Any possible solutions?
No

### Can you identify the location in the driver source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
Can't

**Comment by adishM98** [comment]
Hi @pbjorklund, 

We no longer support the tag tooljet/tooljet-client-ce:latest and tooljet/tooljet-server-ce:latest. We have moved to a single tag which is tooljet/tooljet:latest.

**Comment by pbjorklund** [comment]
Ok, fyi I just followed setup instructions from website on a new machine so docs might need updating. Will try with the other image and see if the migrations are broken in that or not.

**Comment by adishM98** [comment]
Sure, for docker you can refer our docs https://docs.tooljet.com/docs/setup/docker
