### ISSUE TITLE
Tooljet Server Crashing

### ISSUE THREAD

**Issue by cattoman1** [ToolJet/ToolJet#9537]
### Environment
  Docker on Windows.

### What is the expected behaviour?
The Server Starts 

### What is the current behaviour?
It Crashes
with error:
`query: SELECT * FROM current_schema()
2024-04-29 11:46:28 Error during migration run:
2024-04-29 11:46:28 Error: Cannot find module '@tooljet/plugins/dist/server'
2024-04-29 11:46:28 Require stack:
2024-04-29 11:46:28 - /app/server/src/modules/data_sources/query.errors.ts
2024-04-29 11:46:28 - /app/server/src/helpers/utils.helper.ts
2024-04-29 11:46:28 - /app/server/migrations/1677820920004-DropAppVersionIdInAppEnvironments.ts
2024-04-29 11:46:28 - /app/server/node_modules/typeorm/util/ImportUtils.js
2024-04-29 11:46:28 - /app/server/node_modules/typeorm/connection/ConnectionOptionsReader.js
2024-04-29 11:46:28 - /app/server/node_modules/typeorm/globals.js
2024-04-29 11:46:28 - /app/server/node_modules/typeorm/commands/SchemaSyncCommand.js
2024-04-29 11:46:28 - /app/server/node_modules/typeorm/cli.js
2024-04-29 11:46:28     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2024-04-29 11:46:28     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/app/server/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
2024-04-29 11:46:28     at Function.Module._resolveFilename (/app/server/node_modules/tsconfig-paths/src/register.ts:90:36)
2024-04-29 11:46:28     at Function.Module._load (node:internal/modules/cjs/loader:922:27)
2024-04-29 11:46:28     at Module.require (node:internal/modules/cjs/loader:1143:19)
2024-04-29 11:46:28     at require (node:internal/modules/cjs/helpers:119:18)
2024-04-29 11:46:28     at Object.<anonymous> (/app/server/src/modules/data_sources/query.errors.ts:1:1)
2024-04-29 11:46:28     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2024-04-29 11:46:28     at Module.m._compile (/app/server/node_modules/ts-node/src/index.ts:1618:23)
2024-04-29 11:46:28     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
2024-04-29 11:46:28   code: 'MODULE_NOT_FOUND',
2024-04-29 11:46:28   requireStack: [
2024-04-29 11:46:28     '/app/server/src/modules/data_sources/query.errors.ts',
2024-04-29 11:46:28     '/app/server/src/helpers/utils.helper.ts',
2024-04-29 11:46:28     '/app/server/migrations/1677820920004-DropAppVersionIdInAppEnvironments.ts',
2024-04-29 11:46:28     '/app/server/node_modules/typeorm/util/ImportUtils.js',
2024-04-29 11:46:28     '/app/server/node_modules/typeorm/connection/ConnectionOptionsReader.js',
2024-04-29 11:46:28     '/app/server/node_modules/typeorm/globals.js',
2024-04-29 11:46:28     '/app/server/node_modules/typeorm/commands/SchemaSyncCommand.js',
2024-04-29 11:46:28     '/app/server/node_modules/typeorm/cli.js'
2024-04-29 11:46:28   ]
2024-04-29 11:46:28 }`
### How to reproduce the issue?

1.run docker compose up -d in the directory where tooljet is downloaded and you setup the .env file
2.look in the Log

### Screenshots or Screencast

![image](https://github.com/ToolJet/ToolJet/assets/104154537/bd71f034-a09c-4619-8cb3-a626bd84a2cd)

### Any possible solutions?
Unknown

### Can you identify the location in the driver source code where the problem exists?
no

**Comment by adishM98** [comment]
Hi @cattoman1, 

Could you try to build the plugins again and then start the server.

**Comment by alexlazellari** [comment]
As @adishM98 mentioned, try to run: docker compose run --rm  plugins npm run build:plugins

**Comment by IWang20** [comment]
Hey, I ran into the same error, using https://docs.tooljet.com/docs/contributing-guide/setup/docker/

I got around it by running `docker compose restart server` 
After you let it run for a while it should allow localhost to run.

**Comment by PriteshKiri** [comment]
Hey! 

I hope your issue has been resolved. 

If you're still experiencing any difficulties, feel free to reach out to us on our [Slack community](https://www.tooljet.com/slack), and we'll be happy to assist you further. 

Closing the issue for now.
